// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebInstituto;

#nullable disable

namespace WebInstituto.Migrations
{
    [DbContext(typeof(DBSqlite))]
    [Migration("20250403080454_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("WebInstituto.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdProfesor")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdProfesor");

                    b.ToTable("Asignatura");
                });

            modelBuilder.Entity("WebInstituto.Models.AsignaturaPersona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAlumno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdAlumno");

                    b.HasIndex("IdAsignatura");

                    b.ToTable("AsignaturaPersona");
                });

            modelBuilder.Entity("WebInstituto.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("WebInstituto.Models.Persona", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AsignaturaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContrasenyaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Teacher")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("WebInstituto.Models.Asignatura", b =>
                {
                    b.HasOne("WebInstituto.Models.Persona", "Profesor")
                        .WithMany("AsignaturasImpartidas")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("WebInstituto.Models.AsignaturaPersona", b =>
                {
                    b.HasOne("WebInstituto.Models.Persona", "Alumno")
                        .WithMany("AsignaturasAlumno")
                        .HasForeignKey("IdAlumno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebInstituto.Models.Asignatura", "Asignatura")
                        .WithMany("Alumnos")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("WebInstituto.Models.Horario", b =>
                {
                    b.HasOne("WebInstituto.Models.Asignatura", "Asignatura")
                        .WithMany("Horarios")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("WebInstituto.Models.Persona", b =>
                {
                    b.HasOne("WebInstituto.Models.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("AsignaturaId");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("WebInstituto.Models.Asignatura", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("WebInstituto.Models.Persona", b =>
                {
                    b.Navigation("AsignaturasAlumno");

                    b.Navigation("AsignaturasImpartidas");
                });
#pragma warning restore 612, 618
        }
    }
}
